<a href="https://colab.research.google.com/github/SHAHAB-UDDIN54/Machine_learning-with-Shah/blob/main/imputing_category_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
import pandas as pd
dataset = pd.read_excel(r"/content/ml_practice_dataset 2.xlsx")
dataset.head(5)

,ID,Name,Age,Salary,Department,Experience_Years,City,Performance,Joining_Year,Bonus
0,1.0,Julia,55.0,118556.0,HR,37.0,London,NaN,2011.0,NaN
1,2.0,Grace,NaN,999999.0,IT,NaN,NaN,Good,2022.0,6422.0
2,3.0,NaN,NaN,107660.0,NaN,NaN,Delhi,NaN,2011.0,NaN
3,4.0,Julia,35.0,NaN,HR,NaN,Berlin,NaN,NaN,NaN
4,5.0,Alice,NaN,999999.0,HR,7.0,London,Good,2014.0,8137.0

In [5]:
dataset.isnull().sum()

ID                   2
Name                 6
Age                 29
Salary               4
Department           5
Experience_Years    24
City                 3
Performance         11
Joining_Year         4
Bonus               21
dtype: int64

In [6]:
dataset.notnull().sum()

ID                  48
Name                44
Age                 21
Salary              46
Department          45
Experience_Years    26
City                47
Performance         39
Joining_Year        46
Bonus               29
dtype: int64

In [7]:
dataset.shape

(50, 10)

In [8]:
dataset.describe()

,ID,Age,Salary,Experience_Years,Joining_Year,Bonus
count,48.000000,21.000000,46.000000,26.000000,46.000000,29.00000
mean,24.770833,39.904762,514828.304348,18.653846,2011.673913,6053.62069
std,15.184314,11.678633,470160.678234,13.460884,7.357700,2614.90895
min,1.000000,20.000000,24114.000000,0.000000,2000.000000,620.00000
25%,11.750000,33.000000,65575.250000,7.000000,2006.000000,4389.00000
50%,24.500000,37.000000,118221.500000,18.000000,2010.500000,6928.00000
75%,38.250000,52.000000,999999.000000,32.500000,2019.250000,8137.00000
max,50.000000,60.000000,999999.000000,40.000000,2024.000000,9890.00000

In [9]:
dataset.fillna("notfill").head(10)

,ID,Name,Age,Salary,Department,Experience_Years,City,Performance,Joining_Year,Bonus
0,1.0,Julia,55.0,118556.0,HR,37.0,London,notfill,2011.0,notfill
1,2.0,Grace,notfill,999999.0,IT,notfill,notfill,Good,2022.0,6422.0
2,3.0,notfill,notfill,107660.0,notfill,notfill,Delhi,notfill,2011.0,notfill
3,4.0,Julia,35.0,notfill,HR,notfill,Berlin,notfill,notfill,notfill
4,5.0,Alice,notfill,999999.0,HR,7.0,London,Good,2014.0,8137.0
5,6.0,Helen,notfill,999999.0,Sales,notfill,Toronto,Good,2011.0,8454.0
6,7.0,Ian,notfill,45543.0,Marketing,notfill,Berlin,Good,2017.0,2540.0
7,8.0,Helen,30.0,999999.0,Finance,notfill,Delhi,Average,2010.0,notfill
8,9.0,Bob,36.0,89912.0,IT,notfill,Delhi,Good,2001.0,4602.0
9,5.0,notfill,26.0,99495.0,IT,15.0,Delhi,notfill,2020.0,notfill

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                48 non-null     float64
 1   Name              44 non-null     object
 2   Age               21 non-null     float64
 3   Salary            46 non-null     float64
 4   Department        45 non-null     object
 5   Experience_Years  26 non-null     float64
 6   City              47 non-null     object
 7   Performance       39 non-null     object
 8   Joining_Year      46 non-null     float64
 9   Bonus             29 non-null     float64
dtypes: float64(6), object(4)
memory usage: 4.0+ KB

In [11]:
dataset.fillna(method="bfill",axis=1)
dataset.head(5)

/tmp/ipykernel_3734/3453731171.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dataset.fillna(method="bfill",axis=1)

,ID,Name,Age,Salary,Department,Experience_Years,City,Performance,Joining_Year,Bonus
0,1.0,Julia,55.0,118556.0,HR,37.0,London,NaN,2011.0,NaN
1,2.0,Grace,NaN,999999.0,IT,NaN,NaN,Good,2022.0,6422.0
2,3.0,NaN,NaN,107660.0,NaN,NaN,Delhi,NaN,2011.0,NaN
3,4.0,Julia,35.0,NaN,HR,NaN,Berlin,NaN,NaN,NaN
4,5.0,Alice,NaN,999999.0,HR,7.0,London,Good,2014.0,8137.0

In [12]:
dataset.fillna(method="ffill")
dataset.head(5)

/tmp/ipykernel_3734/3198269973.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dataset.fillna(method="ffill")

,ID,Name,Age,Salary,Department,Experience_Years,City,Performance,Joining_Year,Bonus
0,1.0,Julia,55.0,118556.0,HR,37.0,London,NaN,2011.0,NaN
1,2.0,Grace,NaN,999999.0,IT,NaN,NaN,Good,2022.0,6422.0
2,3.0,NaN,NaN,107660.0,NaN,NaN,Delhi,NaN,2011.0,NaN
3,4.0,Julia,35.0,NaN,HR,NaN,Berlin,NaN,NaN,NaN
4,5.0,Alice,NaN,999999.0,HR,7.0,London,Good,2014.0,8137.0

In [13]:
dataset["Name"].mode()

0    Eva
Name: Name, dtype: object